### ISSUE TITLE
1D fft?

### ISSUE THREAD

**Issue by makarandtapaswi** [locuslab/pytorch_fft#1]
Not sure this is within the scope of this project, or whether this is on a roadmap, but would it be nice to also wrap 1D FFTs? Something like spectral-lib (https://github.com/jnhwkim/spectral-lib) with PyTorch?

**Comment by riceric22** [comment]
1D and 3D FFT would both be great additions, though I haven't implemented them yet since I haven't had an immediate need for them. 

I believe this would be possible by inserting a few well-placed macros (using the pytorch generics).

**Comment by riceric22** [comment]
Actually, I went ahead and added the macros, so there is now both 1D and 3D FFT support.

**Comment by makarandtapaswi** [comment]
Thanks a lot!
