### ISSUE TITLE
pip install issue: libcufft.so.8.0 not found

### ISSUE THREAD

**Issue by kediamanav** [locuslab/pytorch_fft#19]
After running: pip install pytorch-fft, and importing the library I get the following error: ImportError: libcufft.so.8.0: cannot open shared object file: No such file or directory

I am using Python 2.7 and torch 0.2 as I can see from pip freeze. Is there some other dependency which I am missing?

**Comment by riceric22** [comment]
You need to have CuFFT as well, since this is a wrapper around that library.

**Comment by xingdi1990** [comment]
I met the same issue there. Any explains to the solution "You need to have CuFFT as well, since this is a wrapper around that library"?

**Comment by riceric22** [comment]
You need to properly install CuFFT from here https://developer.nvidia.com/cufft. However, I **strongly** recommend not using this library anymore and instead use the native FFT built-ins in PyTorch which have existed since 0.4+.
