### ISSUE TITLE
Batchwise fft

### ISSUE THREAD

**Issue by MdAsifKhan** [locuslab/pytorch_fft#20]
Hey,
fft computation works fine in an online training. However, it doesn't work for batch data. I tried with mini-batches where rows are samples and columns are features. It seems fft function computes transform of entire matrix instead of each row. I also tried reshaping matrix into 3-D tensor (batch_size, 1, num_features). This too doesn't work. 
Is it possible to do fft row-wise or for multiple instance at once ? 

Thanks,
Asif

**Comment by riceric22** [comment]
Sorry, this issue slipped passed me. The FFT functions already work in batch mode, where a d-dimensional FFT transform will implicitly do the FFT in batches over all but the last d dimensions.
