### ISSUE TITLE
pip install not working due to cuda.h missing error

### ISSUE THREAD

**Issue by ycemsubakan** [locuslab/pytorch_fft#21]
I have tried pip install pytorch-fft, on two different machines with gpus, and on both I am getting this error:
venv/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:9:18: fatal error: cuda.h: No such file or directory

I tried python 2.7 and 3.6. I also tried to install without using a virtual environment. 

P.S.: I first got the error which says the package cffi was missing. I installed that package, and now I am getting this error. 

I would appreciate your help!

**Comment by riceric22** [comment]
You also need to have cuda installed, cuda.h is a dependency from cuda

**Comment by ycemsubakan** [comment]
I know, I am using cuda 8.0 For some reason it is not accessing cuda.h .

**Comment by riceric22** [comment]
Make sure cuda.h is in your path

**Comment by ycemsubakan** [comment]
Okay, I have added this to my path:
/usr/local/cuda-8.0/targets/x86_64-linux/include/cuda.h

And it still doesn't work, I am getting the same error. Is this the exact path I am supposed to add? 

I think the error says that the installation looks at this directory and cannot find cuda.h:
~/venv3.6/lib/python3.6/site-packages/torch/lib/include/THC

And there is no cuda.h under this directory... What should I do?

**Comment by riceric22** [comment]
Try following the instructions on the cuda quick start guide, they describe how you can update your corresponding path variables (you'll need both path and ld_library_path)

http://docs.nvidia.com/cuda/cuda-quick-start-guide/index.html

**Comment by ycemsubakan** [comment]
Path and ld_library_path are properly set-up for me. As I have said, my pytorch works perfectly fine with cuda.

**Comment by riceric22** [comment]
Can you try making a soft link from /usr/local/cuda/ to /usr/local/cuda-8.0/ ?

**Comment by ycemsubakan** [comment]
Alright, creating the soft link worked. Thank you!

**Comment by jzbontar** [comment]
I had the same issue. I resolved it by exporting some environmental variables:

$ export C_INCLUDE_PATH=${CUDA_HOME}/include:${C_INCLUDE_PATH}
$ export LIBRARY_PATH=${CUDA_HOME}/lib64:$LIBRARY_PATH
$ pip install pytorch-fft

**Comment by wtliao** [comment]
@ycemsubakan hi, could you tell me how did you create this soft link? I tried as:
sudo ln -s /usr/local/cuda-8.0/  /usr/local/cuda/

then a symbolic linkof cuda-8.0 is created under cuda, which means the path to cuda is /usr/local/cuda/cuda-8.0. So the system can't find the correct path.

In my .bahsrc I have set:
$ export PATH="/usr/local/cuda/cuda-8.0/bin:$PATH"
$ export LD_LIBRARY_PATH="/usr/local/cuda/cuda-8.0/lib64:$LIBRARY_PATH"

And it works well such as with tensorflow-gpu.

I'have been being annoyed by this error for days :(

**Comment by stefbraun** [comment]
@ycemsubakan , how did you create the soft link? can you give the command please?

**Comment by wonderingabout** [comment]
the fix for me was to install `sudo apt-get install nvidia-cuda-toolkit` after `sudo apt-get install -y cuda-9.0`

also on a brand new ubuntu it is not needed to install nvidia-384, just install cuda-9.0 and graphics driver is included in it

all steps from here : 
https://medium.com/@mishra.thedeepak/cuda-and-cudnn-installation-for-tensorflow-gpu-79beebb356d2
and here (change to 3.0.4) : 
https://kezunlin.me/post/dacc4196/

now pycuda works (for tensorrt 3.0.4 tar file install on ubuntu 16.04 - cuda 9.0 deb - cudnn 7.0.5 deb)

![pycuda works](https://user-images.githubusercontent.com/38690718/50424073-e85f0480-085e-11e9-9d1c-a84b78ea7e78.png)

**Comment by Saif-Alhaider** [comment]
Could not find any cudnn.h matching version '7' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1'
Asking for detailed CUDA configuration..
same error please help

**Comment by pranavnijampurkar33** [comment]
> 
> 
> @ycemsubakan , how did you create the soft link? can you give the command please?
Here you go after whole 2 years...!!!
sudo ln -s /usr/local/cuda/ /usr/local/cuda-8.0/

**Comment by hoangdh** [comment]
> I had the same issue. I resolved it by exporting some environmental variables:
> 
> $ export C_INCLUDE_PATH=${CUDA_HOME}/include:${C_INCLUDE_PATH}
> $ export LIBRARY_PATH=${CUDA_HOME}/lib64:$LIBRARY_PATH
> $ pip install pytorch-fft

Additional, you must set CUDA_HOME and add it to $PATH.

```
export CUDA_HOME=/usr/local/cuda
export PATH=${PATH}:${CUDA_HOME}/bin
```
