### ISSUE TITLE
build err

### ISSUE THREAD

**Issue by jiqizaisikao** [locuslab/pytorch_fft#23]
Hi,I tried pip install pytorch-fft it succeed,but when i tried build.py it end with err:
No such file or directory:'/tmp/tmpdq7_hm2i/pytorch_fft._ext.th_fft._th_fft.so'
My  os is ubuntu 16.04 and python 3.6 version

**Comment by riceric22** [comment]
Hi, when installing from source, we need the build.py file to have package=False in the call to create_extension (for creating a pip package, it needs to be True). 

I've updated this in the repository so that the repo is by default installable from source.
