### ISSUE TITLE
pip install problem

### ISSUE THREAD

**Issue by huguyuehuhu** [locuslab/pytorch_fft#32]
when I run pip to install, I got a error below, what is wrong? Thank you 
`pip install pytorch-fft
Collecting pytorch-fft
  Downloading https://files.pythonhosted.org/packages/f6/d8/00edd29004d9943ebd42c665ac6f25ac57c7b9165656da514bb62737d85d/pytorch_fft-0.14.tar.gz
Requirement already satisfied: cffi>=1.0.0 in /datah/gyhu/soft/Anaconda3/envs/gymlab/lib/python3.5/site-packages (from pytorch-fft) (1.10.0)
Requirement already satisfied: pycparser in /datah/gyhu/soft/Anaconda3/envs/gymlab/lib/python3.5/site-packages (from cffi>=1.0.0->pytorch-fft) (2.18)
Building wheels for collected packages: pytorch-fft
  Running setup.py bdist_wheel for pytorch-fft ... error
  Complete output from command /datah/gyhu/soft/Anaconda3/envs/gymlab/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-c68r__q6/pytorch-fft/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-84v_y0fw --python-tag cp35:
  Including CUDA code.
  Including CUDA code.
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/pytorch_fft
  copying pytorch_fft/__init__.py -> build/lib.linux-x86_64-3.5/pytorch_fft
  creating build/lib.linux-x86_64-3.5/pytorch_fft/_ext
  copying pytorch_fft/_ext/__init__.py -> build/lib.linux-x86_64-3.5/pytorch_fft/_ext
  creating build/lib.linux-x86_64-3.5/pytorch_fft/fft
  copying pytorch_fft/fft/fft.py -> build/lib.linux-x86_64-3.5/pytorch_fft/fft
  copying pytorch_fft/fft/__init__.py -> build/lib.linux-x86_64-3.5/pytorch_fft/fft
  copying pytorch_fft/fft/autograd.py -> build/lib.linux-x86_64-3.5/pytorch_fft/fft
  creating build/lib.linux-x86_64-3.5/pytorch_fft/_ext/th_fft
  copying pytorch_fft/_ext/th_fft/__init__.py -> build/lib.linux-x86_64-3.5/pytorch_fft/_ext/th_fft
  running build_ext
  generating cffi module 'build/temp.linux-x86_64-3.5/pytorch_fft._ext.th_fft._th_fft.c'
  creating build/temp.linux-x86_64-3.5
  building 'pytorch_fft._ext.th_fft._th_fft' extension
  creating build/temp.linux-x86_64-3.5/build
  creating build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/tmp
  creating build/temp.linux-x86_64-3.5/tmp/pip-install-c68r__q6
  creating build/temp.linux-x86_64-3.5/tmp/pip-install-c68r__q6/pytorch-fft
  creating build/temp.linux-x86_64-3.5/tmp/pip-install-c68r__q6/pytorch-fft/pytorch_fft
  creating build/temp.linux-x86_64-3.5/tmp/pip-install-c68r__q6/pytorch-fft/pytorch_fft/src
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/datah/gyhu/soft/Anaconda3/envs/gymlab/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include -I/datah/gyhu/soft/Anaconda3/envs/gymlab/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH -I/datah/gyhu/soft/Anaconda3/envs/gymlab/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/THC -I/tmp/pip-install-c68r__q6/pytorch-fft/pytorch_fft/src -I/datah/gyhu/soft/Anaconda3/envs/gymlab/include/python3.5m -c build/temp.linux-x86_64-3.5/pytorch_fft._ext.th_fft._th_fft.c -o build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5/pytorch_fft._ext.th_fft._th_fft.o
  In file included from /datah/gyhu/soft/Anaconda3/envs/gymlab/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                   from build/temp.linux-x86_64-3.5/pytorch_fft._ext.th_fft._th_fft.c:434:
  /datah/gyhu/soft/Anaconda3/envs/gymlab/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:9:18: fatal error: cuda.h: No such file or directory
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pytorch-fft
  Running setup.py clean for pytorch-fft
Failed to build pytorch-fft
Installing collected packages: pytorch-fft
  Running setup.py install for pytorch-fft ... error
    Complete output from command /datah/gyhu/soft/Anaconda3/envs/gymlab/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-c68r__q6/pytorch-fft/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-122qb4h5/install-record.txt --single-version-externally-managed --compile:
    Including CUDA code.
    Including CUDA code.
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/pytorch_fft
    copying pytorch_fft/__init__.py -> build/lib.linux-x86_64-3.5/pytorch_fft
    creating build/lib.linux-x86_64-3.5/pytorch_fft/_ext
    copying pytorch_fft/_ext/__init__.py -> build/lib.linux-x86_64-3.5/pytorch_fft/_ext
    creating build/lib.linux-x86_64-3.5/pytorch_fft/fft
    copying pytorch_fft/fft/fft.py -> build/lib.linux-x86_64-3.5/pytorch_fft/fft
    copying pytorch_fft/fft/__init__.py -> build/lib.linux-x86_64-3.5/pytorch_fft/fft
    copying pytorch_fft/fft/autograd.py -> build/lib.linux-x86_64-3.5/pytorch_fft/fft
    creating build/lib.linux-x86_64-3.5/pytorch_fft/_ext/th_fft
    copying pytorch_fft/_ext/th_fft/__init__.py -> build/lib.linux-x86_64-3.5/pytorch_fft/_ext/th_fft
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-3.5/pytorch_fft._ext.th_fft._th_fft.c'
    creating build/temp.linux-x86_64-3.5
    building 'pytorch_fft._ext.th_fft._th_fft' extension
    creating build/temp.linux-x86_64-3.5/build
    creating build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/tmp
    creating build/temp.linux-x86_64-3.5/tmp/pip-install-c68r__q6
    creating build/temp.linux-x86_64-3.5/tmp/pip-install-c68r__q6/pytorch-fft
    creating build/temp.linux-x86_64-3.5/tmp/pip-install-c68r__q6/pytorch-fft/pytorch_fft
    creating build/temp.linux-x86_64-3.5/tmp/pip-install-c68r__q6/pytorch-fft/pytorch_fft/src
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/datah/gyhu/soft/Anaconda3/envs/gymlab/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include -I/datah/gyhu/soft/Anaconda3/envs/gymlab/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH -I/datah/gyhu/soft/Anaconda3/envs/gymlab/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/THC -I/tmp/pip-install-c68r__q6/pytorch-fft/pytorch_fft/src -I/datah/gyhu/soft/Anaconda3/envs/gymlab/include/python3.5m -c build/temp.linux-x86_64-3.5/pytorch_fft._ext.th_fft._th_fft.c -o build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5/pytorch_fft._ext.th_fft._th_fft.o
    In file included from /datah/gyhu/soft/Anaconda3/envs/gymlab/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                     from build/temp.linux-x86_64-3.5/pytorch_fft._ext.th_fft._th_fft.c:434:
    /datah/gyhu/soft/Anaconda3/envs/gymlab/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:9:18: fatal error: cuda.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/datah/gyhu/soft/Anaconda3/envs/gymlab/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-c68r__q6/pytorch-fft/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-122qb4h5/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-c68r__q6/pytorch-fft/
`

**Comment by riceric22** [comment]
See #21
