### ISSUE TITLE
How to center the zero frequency in FFT's output?

### ISSUE THREAD

**Issue by Lokesh-Boominathan** [locuslab/pytorch_fft#9]
I was wondering if there's an implementation to centre the zero frequency components of the FFT function's output. More or less like Matlab's 'fftshift'. 

Thanks in advance for any help that you can provide.

**Comment by riceric22** [comment]
There's none currently (in this package), but I have implemented what was described in the thread linked to [here ](https://discuss.pytorch.org/t/implementation-of-function-like-numpy-roll/964) (a pytorch implementation of np.roll). It looks like fftshift can be then implemented by calling roll on each axis. 

I can add my roll implementation to the package if you'd find that useful, however it's not an autograd function if that's what you need.

**Comment by Lokesh-Boominathan** [comment]
Yea, am actually looking for a way to use autograd after fftshift. However, if possible, can you add the implementation you mentioned?

**Comment by riceric22** [comment]
I've added it under the fft module in `fft.py` with the other helper functions. It has the signature `roll_n(X, axis, n)`, where `X` is the tensor to be rolled, `axis` is the axis to be rolled, and `n` is the number of spaces to roll. If you make this into an autograd-able function, send in a PR!

**Comment by keunhong** [comment]
I believe the following does the trick. The input is assumed to be batched (the first dim is the batch dimension).

```
def fftshift(real, imag):
    for dim in range(1, len(real.size())):
        real = fft.roll_n(real, axis=dim, n=real.size(dim)//2)
        imag = fft.roll_n(imag, axis=dim, n=imag.size(dim)//2)
    return real, imag
```

**Comment by vmos1** [comment]
In 2020, and this is still useful. 
The above code didn't match the results of `spicy.fftshift`. Had to modify a bit.
**pytorch** now has `torch.roll`
(The 0 in the `range` is essential )
The following code works for me (now):

```
def torch_fftshift(real, imag):
    for dim in range(0, len(real.size())):
        real = torch.roll(real, dims=dim, shifts=real.size(dim)//2)
        imag = torch.roll(imag, dims=dim, shifts=imag.size(dim)//2)
    return real, imag
```

**Comment by the-lay** [comment]
@vmos1 PyTorch 1.8 will (finally) include more FFT functionality, including fftshift. However, until then, this is the best approach.
